### ISSUE TITLE
Fazer apresentação Milestone 2

### ISSUE THREAD

**Issue by Patricia-Dias** [fMart8421/Camellia-Cultivar#4]
- [x] Requirements elicitation
  - [x] Define goals 
  - [x] State of the art (improved: related work + technologies) 
  - [x] Collect information: documents, interviews
- [x] Functional and non-functional requirements
  - [x] Actors, uses cases and other
- [x] System Architecture
  - [x] Skeleton structure of the system
- [x] Design mock-ups as soon as possible
