### ISSUE TITLE
Create Quizzes Page

### ISSUE THREAD

**Issue by tiagomrm** [fMart8421/Camellia-Cultivar#8]
### Task List
- [x] Create quizz card component
- [ ] Create image viewing modal component
- [x] Implement rest of the page
